### ISSUE TITLE
Falha na verificação de disponibilidade da api

### ISSUE THREAD

**Issue by DevPauloDias** [cnpj-ws/consultar-cnpj#2]
Aparentemente, a biblioteca não está tratando adequadamente quando a api não está disponível. Segue o console do erro: 

/app/node_modules/consultar-cnpj/src/index.js:25
        reject(error.response.data);
                              ^

TypeError: Cannot read properties of undefined (reading 'data')
    at <anonymous> (/app/node_modules/consultar-cnpj/src/index.js:25:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.1

**Comment by tirabassi** [comment]
O pacote foi atualizado com a correção no npm
