### ISSUE TITLE
Consulta CNPJ não retorna Inscrições Estaduais

### ISSUE THREAD

**Issue by DavidCFreire** [cnpj-ws/consultar-cnpj#6]
Ao fazer consulta do CNPJ 48922412000105 não está retornando os dados de inscrição estadual e esse CNPJ tem ao menos 2 inscrições estaduais na Paraíba e no Rio Grande do Norte.

`{
    "cnpj_raiz": "48922412",
    "razao_social": "CARUARU 20 NATAL COMERCIO LTDA",
    "capital_social": "49000.00",
    "responsavel_federativo": "",
    "atualizado_em": "2024-05-11T03:00:00.000Z",
    "porte": {
        "id": "01",
        "descricao": "Micro Empresa"
    },
    "natureza_juridica": {
        "id": "2062",
        "descricao": "Sociedade Empresária Limitada"
    },
    "qualificacao_do_responsavel": {
        "id": 49,
        "descricao": "Sócio-Administrador "
    },
    "socios": [
        {
            "cpf_cnpj_socio": "***922724**",
            "nome": "MAXSANDRA ALMEIDA OLIVEIRA",
            "tipo": "Pessoa Física",
            "data_entrada": "2023-11-16",
            "cpf_representante_legal": "***000000**",
            "nome_representante": null,
            "faixa_etaria": "21 a 30 anos",
            "atualizado_em": "2024-04-13T03:00:00.000Z",
            "pais_id": "1058",
            "qualificacao_socio": {
                "id": 22,
                "descricao": "Sócio"
            },
            "qualificacao_representante": null,
            "pais": {
                "id": "1058",
                "iso2": "BR",
                "iso3": "BRA",
                "nome": "Brasil",
                "comex_id": "105"
            }
        },
        {
            "cpf_cnpj_socio": "***396914**",
            "nome": "HELDER DE PAIVA ARNAUD FREITAS FILHO",
            "tipo": "Pessoa Física",
            "data_entrada": "2022-12-19",
            "cpf_representante_legal": "***000000**",
            "nome_representante": null,
            "faixa_etaria": "21 a 30 anos",
            "atualizado_em": "2024-04-13T03:00:00.000Z",
            "pais_id": "1058",
            "qualificacao_socio": {
                "id": 49,
                "descricao": "Sócio-Administrador "
            },
            "qualificacao_representante": null,
            "pais": {
                "id": "1058",
                "iso2": "BR",
                "iso3": "BRA",
                "nome": "Brasil",
                "comex_id": "105"
            }
        }
    ],
    "simples": {
        "simples": "Sim",
        "data_opcao_simples": "2022-12-19",
        "data_exclusao_simples": null,
        "mei": "Não",
        "data_opcao_mei": null,
        "data_exclusao_mei": null,
        "atualizado_em": "2024-04-13T03:00:00.000Z"
    },
    "estabelecimento": {
        "cnpj": "48922412000105",
        "atividades_secundarias": [
            {
                "id": "4120400",
                "secao": "F",
                "divisao": "41",
                "grupo": "41.2",
                "classe": "41.20-4",
                "subclasse": "4120-4/00",
                "descricao": "Construção de edifícios"
            },
            {
                "id": "4213800",
                "secao": "F",
                "divisao": "42",
                "grupo": "42.1",
                "classe": "42.13-8",
                "subclasse": "4213-8/00",
                "descricao": "Obras de urbanização - ruas, praças e calçadas"
            },
            {
                "id": "4299599",
                "secao": "F",
                "divisao": "42",
                "grupo": "42.9",
                "classe": "42.99-5",
                "subclasse": "4299-5/99",
                "descricao": "Outras obras de engenharia civil não especificadas anteriormente"
            },
            {
                "id": "4311801",
                "secao": "F",
                "divisao": "43",
                "grupo": "43.1",
                "classe": "43.11-8",
                "subclasse": "4311-8/01",
                "descricao": "Demolição de edifícios e outras estruturas"
            },
            {
                "id": "4399103",
                "secao": "F",
                "divisao": "43",
                "grupo": "43.9",
                "classe": "43.99-1",
                "subclasse": "4399-1/03",
                "descricao": "Obras de alvenaria"
            },
            {
                "id": "4399199",
                "secao": "F",
                "divisao": "43",
                "grupo": "43.9",
                "classe": "43.99-1",
                "subclasse": "4399-1/99",
                "descricao": "Serviços especializados para construção não especificados anteriormente"
            },
            {
                "id": "7111100",
                "secao": "M",
                "divisao": "71",
                "grupo": "71.1",
                "classe": "71.11-1",
                "subclasse": "7111-1/00",
                "descricao": "Serviços de arquitetura"
            },
            {
                "id": "7119703",
                "secao": "M",
                "divisao": "71",
                "grupo": "71.1",
                "classe": "71.19-7",
                "subclasse": "7119-7/03",
                "descricao": "Serviços de desenho técnico relacionados à arquitetura e engenharia"
            },
            {
                "id": "7119799",
                "secao": "M",
                "divisao": "71",
                "grupo": "71.1",
                "classe": "71.19-7",
                "subclasse": "7119-7/99",
                "descricao": "Atividades técnicas relacionadas à engenharia e arquitetura não especificadas anteriormente"
            }
        ],
        "cnpj_raiz": "48922412",
        "cnpj_ordem": "0001",
        "cnpj_digito_verificador": "05",
        "tipo": "Matriz",
        "nome_fantasia": "SST SERTAO",
        "situacao_cadastral": "Ativa",
        "data_situacao_cadastral": "2022-12-19",
        "data_inicio_atividade": "2022-12-19",
        "nome_cidade_exterior": null,
        "tipo_logradouro": "RUA",
        "logradouro": "FUNDADOR ROCHA",
        "numero": "27",
        "complemento": "SALA  1                   ANEXO 1",
        "bairro": "CENTRO",
        "cep": "58884000",
        "ddd1": "83",
        "telefone1": "96361218",
        "ddd2": null,
        "telefone2": null,
        "ddd_fax": null,
        "fax": null,
        "email": "sst.sertao@gmail.com",
        "situacao_especial": null,
        "data_situacao_especial": null,
        "atualizado_em": "2024-04-13T03:00:00.000Z",
        "atividade_principal": {
            "id": "7112000",
            "secao": "M",
            "divisao": "71",
            "grupo": "71.1",
            "classe": "71.12-0",
            "subclasse": "7112-0/00",
            "descricao": "Serviços de engenharia"
        },
        "pais": {
            "id": "1058",
            "iso2": "BR",
            "iso3": "BRA",
            "nome": "Brasil",
            "comex_id": "105"
        },
        "estado": {
            "id": 15,
            "nome": "Paraíba",
            "sigla": "PB",
            "ibge_id": 25
        },
        "cidade": {
            "id": 1298,
            "nome": "Catolé do Rocha",
            "ibge_id": 2504306,
            "siafi_id": "1987"
        },
        "motivo_situacao_cadastral": null,
        "inscricoes_estaduais": []
    }
}`

Retorno que estou recebendo da API

**Comment by tirabassi** [comment]
Boa tarde,

A API não tem integração com todos os estados, veja abaixo os estados homologados
https://www.cnpj.ws/docs/modelos-dados/inscricoes-estaduais

A API pode trazer alguns dados de outros estamos mas não garante que todos os dados desses outros estados estejam na base
