### ISSUE TITLE
Inscrições estaduais de MEI

### ISSUE THREAD

**Issue by Dufayel** [cnpj-ws/consultar-cnpj#7]
Bom dia,

Segundo documentação para o estado do RS as inscrições estaduais são disponibilizadas, porém quando o CNPJ é de um MEI a inscrição estadual está vindo sempre como inativa, como exemplo tenho o CNPJ 27.703.613/0001-41, porém isso se repete com todos os CNPJs de MEI que consultamos no RS.

![image](https://github.com/user-attachments/assets/586d1ab8-4546-44e7-b59d-70e57d89139c)

**Comment by tirabassi** [comment]
Boa tarde,

Os registros foram reprocessados e o status agora está correto:

![image](https://github.com/user-attachments/assets/10dd8ac2-216c-4993-901b-08618030d2f1)
